import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Header, NavItem } from "@/components/shared/Header/Header";
import { HeaderMobile } from "@/components/shared/Header/HeaderMobile";
import logoFullWhite from "@/assets/images/logo/LogoFullWhite.png";

const poppins = Poppins({
  subsets: ["latin", "latin-ext"],
  display: "swap",
  weight: ["400", "600", "700", "900"],
  variable: "--font-base",
});

export const metadata: Metadata = {
  title: "Glazlukasz.pl",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerProps = {
    navItems: [
      { id: 1, label: "Strona Główna", href: "/" },
      { id: 2, label: "Usługi", href: "/uslugi" },
      { id: 3, label: "Realizacje", href: "/realizacje" },
      { id: 4, label: "O Mnie", href: "/o-mnie" },
      { id: 5, label: "Kontakt", href: "/kontakt" },
    ] as NavItem[],
    logoSrc: logoFullWhite,
    logoAlt: "Logo Twojej Marki",
    logoHref: "/",
  };

  return (
    <html lang="en" className={poppins.className}>
      <body className={"antialiased"}>
        <HeaderMobile {...headerProps} />
        <Header {...headerProps} />
        <main>{children}</main>
      </body>
    </html>
  );
}
