import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin", "latin-ext"],
  display: "swap",
  weight: ["400", "600", "700", "900"],
  variable: "--font-base",
});
export const metadata: Metadata = {
  title: "Glazlukasz.pl",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body className={"antialiased"}>{children}</body>
    </html>
  );
}
